name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dir check
    - name: Curl for Github Actions
      uses: sozo-design/curl@v1.0.2
      run: sudo chmod 777 ./oclt_code
    - name: curl install
      run: sudo apt-get install libcurl
    - name: g++make
      run: g++ oclt_code/launch.cpp -l curl -o OpenCppLangTab
    - name: make distcheck
      run: make distcheck
