name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dir make
      run: sudo chmod 777./oclt_code
    - name: curlsetup
      run: sudo apt-get install curl
    - name: g++make
      run: oclt_code/make.sh
    - name: make distcheck
      run: make distcheck
