name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dir check
      run: sudo chmod 777 ./oclt_code
    - name: curl install
      run: sudo apt-get install libcurl4-openssl-dev
    - name: g++make
      run: g++ oclt_code/launch.cpp -l curl -o Calcium_for_linux
    - name: 'Upload artifacts'
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: 'Artifacts'
        path: Calcium_for_linux
